name: workflow pylint and nosetests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: run pylint
        run: pipenv run pylint app
      - name: run nosetests
        run: pipenv run nosetests

  review:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref != 'refs/heads/main' }}
      steps:
        - uses: actions/checkout@v2
        - name: Create pull request
          uses: repo-sync/pull-request@v2
          with:
            destination_branch: "main"
            github_token: ${{ secrets.GITHUB_TOKEN }}
            pr_title: "Awesome PR by ${{ github.actor }}"
